/altug/FO-5-Order-Payment
alperenustun/food-order-app pull request #2
Opened 2024-04-03 15:54 UTC by altugaltuner

2024-04-04 14:46 UTC, alperenustun requested changes
- [ ] package.json'da değişiklik olmaması gerek.
- [ ] App.jsx'deki değişiklikler olmaması gerek.

2024-04-25 22:33 UTC, altugaltuner commented
I have finished the requested changes 3 weeks ago, it should be okay

2024-05-02 15:01 UTC, alperenustun requested changes
```
@media (max-width: 585px) {
<style>
    .order-payment {
        margin: 0px 27px 0px 0px;
    }
}
```

bunu kaldırıp bir de ana sayfadan component'i kaldırıp merge edebilirsin.

2024-05-02 15:01 UTC, alperenustun commented on src/pages/OrderPaymentPage/OrderPaymentPage.scss
> +body {
body yerine sadece kendi elemanının class adlarını kulanacaksın.

2024-05-02 15:01 UTC, alperenustun commented on src/pages/OrderPaymentPage/OrderPaymentPage.scss
> +    input::placeholder {
bütün hepsi class adı ile olsun.

2024-05-03 12:51 UTC, merged